### ISSUE TITLE
Problem with linear system solution through cholesky decomposition

### ISSUE THREAD

**Issue by okamiRvS** [xmlyqing00/Cholmod-Scikit-Sparse-Windows#4]
I followed all the [instructions](https://github.com/xmlyqing00/Cholmod-Scikit-Sparse-Windows), when I execute cholesky decomposition function works, but then it return me an error when I try to solve the system. In particular, I can do the first line, but not  the last line of the following code:

`factor = cholesky(A)`
`x = factor(b)`

the error that I received is:
`SystemError: <sksparse.cholmod.Factor object at 0x0000010810BC93A0> returned a result with an error set`

Also, I debugged [test_cholmod.py](https://github.com/xmlyqing00/Cholmod-Scikit-Sparse-Windows/blob/master/scikit-sparse-0.4.3/sksparse/test_cholmod.py) and it give me the same errors but I haven't idea of how solve thise issue.

Thank you so much,
Umberto.

**Comment by okamiRvS** [comment]
Ok I resolved, not using scikit-sparse-0.4.3, but the last version 0.4.4 downloanding it [here](https://github.com/scikit-sparse/scikit-sparse/).

I changed the setup.py of 0.4.4 version with this [setup.py](https://github.com/xmlyqing00/Cholmod-Scikit-Sparse-Windows/blob/master/scikit-sparse-0.4.3/setup.py).

**Comment by xmlyqing00** [comment]
Hi @okamiRvS , Thank you for your information. That's very helpful.

I will consider upgrading my scikit-sparse version from 0.4.3 to 0.4.4
