### ISSUE TITLE
How to use GPU acceleration?

### ISSUE THREAD

**Issue by zhenshan0127** [xmlyqing00/Cholmod-Scikit-Sparse-Windows#6]
Hello,

Could you pleaes give me some suggestions about GPU acceleration when using cholesky?

Thank you for your time!

**Comment by xmlyqing00** [comment]
Thanks for your interest in my project. Sorry that I have no idea how to do that in GPU mode. I think the Sksparse package only exposes some functions from the code that is written in the CPU, which has been done for years. So maybe you can check other repositories or use PyTorch to implement the GPU Cholesky decomposition.

**Comment by zhenshan0127** [comment]
Thank you for reply!

Your suggestions are useful! I will try it. I need to process very large sparse matrix, and now it costs almost 25 minutes for each one.

**Comment by xmlyqing00** [comment]
I'm familiar with using PyTorch to do some matrix arithmetic. But the basic class in PyTorch is Tensor, which is used for dense data. I'm not sure whether PyTorch has a sparse data structure to solve your problem. Good luck!
